### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by easonyen16** [bobbytrapz/autosr#2]
**Describe the bug**
Autosr can't show any showroom channel or download any showroom stream
This problem shows on both linux and macos version, and both on Experimental and Version 7

**Screenshots**
<img width="976" alt="截圖 2023-06-17 下午8 53 17" src="https://github.com/bobbytrapz/autosr/assets/57711962/eabc5e02-2f43-4760-817a-215feb997a13">

**System Information:**
Use 'autosr version' to get version information.
 - OS: [mac OS]
 - OS: [6.1.21-v8+ GNU/Linux]
 - Version [8]
 - Version [7]

**Comment by easonyen16** [comment]
Update:
It only can show some of the channels
I've enter about 600 channels, and it only will show about 100 of them.
<img width="1552" alt="截圖 2023-06-17 下午9 24 25" src="https://github.com/bobbytrapz/autosr/assets/57711962/a1df163e-44f9-4611-8edd-4e4c06e07ccd">
the channel that doesn't show will still download, but the file won't be in the folder of channel name, and the file name won't have the channel name too.
<img width="863" alt="截圖 2023-06-17 下午9 27 02" src="https://github.com/bobbytrapz/autosr/assets/57711962/864e56b7-4a39-4643-b2be-b94b0ac61242">

**Comment by bobbytrapz** [comment]
Thanks. I'm looking into it. Recent changes to Showroom has created some issues. It may take a few days to resolve.

**Comment by bobbytrapz** [comment]
Version 8 may have addressed the issues you mentioned. 

To update to the latest version, please run the following command: 'autosr update'

You appear to be using a Raspberry Pi. Please note that autosr v8 requires Headless Chrome, which will require more resources than before.

I might have to consider adding options to allow customization for performance.

**Comment by easonyen16** [comment]
Than you for the update!
I have try it, and it works now.
I use raspberry pi 4b 8G to run it, it takes me about 20 minutes to track the 500 members list.

**Comment by easonyen16** [comment]
I have try a few day, in the older version, using raspberry pi it can record up to 60 live at the same time, but it can only record about 30 live at the same time.
